name: Run Protractor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install @angular/cli@latest

    - name: Start application
      run: |
        Start-Process 'npx' -ArgumentList 'ng serve --port 4200' -NoNewWindow
        Start-Sleep -Seconds 30  # Adjust sleep time based on how long your application takes to start

    - name: Wait for application to be ready
      run: |
        $maxAttempts = 10
        $attempt = 0
        while ($attempt -lt $maxAttempts) {
          try {
            $response = Invoke-WebRequest -Uri http://localhost:4200
            if ($response.StatusCode -eq 200) {
              Write-Output "Application is ready."
              break
            }
          } catch {
            Write-Output "Application not ready yet, retrying..."
          }
          Start-Sleep -Seconds 10
          $attempt++
        }
        if ($attempt -eq $maxAttempts) {
          throw "Application did not start within the maximum wait time."
        }

    - name: Download ChromeDriver
      run: npm install chromedriver@latest

    - name: Start Selenium server
      run: |
        Start-Process 'npx' -ArgumentList 'webdriver-manager start' -NoNewWindow
        Start-Sleep -Seconds 30  # Adjust sleep time based on how long the WebDriver takes to start

    - name: Wait for Selenium server to be ready
      run: |
        $maxAttempts = 10
        $attempt = 0
        while ($attempt -lt $maxAttempts) {
          try {
            $response = Invoke-WebRequest -Uri http://localhost:4444/wd/hub
            if ($response.StatusCode -eq 200) {
              Write-Output "Selenium server is ready."
              break
            }
          } catch {
            Write-Output "Selenium server not ready yet, retrying..."
          }
          Start-Sleep -Seconds 10
          $attempt++
        }
        if ($attempt -eq $maxAttempts) {
          throw "Selenium server did not start within the maximum wait time."
        }

    - name: Run Protractor tests
      run: npx protractor protractor.conf.js
